### ISSUE TITLE
Package not working as global

### ISSUE THREAD

**Issue by cesgarpas** [pafmon/oas-wizard#16]
Error: 
```
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open './templates/basic.yaml'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.<anonymous> (C:\Users\cesga\AppData\Roaming\npm\node_modules\oas-wizard\commands.js:8:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\cesga\AppData\Roaming\npm\node_modules\oas-wizard\index.js:10:21) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './templates/basic.yaml'
}
```

**Comment by cesgarpas** [comment]
Added to all involved files `#!/usr/bin/env node` and joined the path of the template with `path.join(__dirname, './templates/basic.yaml')`
